services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root                          # 👈 Run as root to avoid Docker socket permission denied
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - .jenkins:/var/jenkins_home
    restart: unless-stopped
